# Generated by Django 4.1.7 on 2023-09-24 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Departments", "0002_department_client"),
        ("Nurses", "0002_nurse_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nurse",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Departments.department"
            ),
        ),
    ]
