# Generated by Django 4.1.7 on 2023-09-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Nurses", "0004_remove_nurse_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="nurse",
            name="department",
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
