# Generated by Django 4.2.4 on 2023-08-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabTests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtest",
            name="doctor_first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="labtest",
            name="doctor_last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="labtest",
            name="patient_first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="labtest",
            name="patient_last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
