version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=MAIN.settings.production
    env_file:
      - .env  # This line specifies to use the .env file for environment. variables
    ports:
      - "8000:8000"
    depends_on:
      - db
  

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
