version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development  
    env_file:
      - .env  
    ports:
      - "8000:8000"
