# Generated by Django 4.1.7 on 2023-11-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0010_remove_feedback_feedback_id_feedback_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="id",
        ),
        migrations.AddField(
            model_name="feedback",
            name="feedback_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
