# Generated by Django 4.1.7 on 2023-11-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0011_remove_feedback_id_feedback_feedback_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="feedback_id",
        ),
        migrations.AddField(
            model_name="feedback",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
