# Generated by Django 4.1.7 on 2023-09-22 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0004_feedback_client"),
    ]

    operations = []
