# Generated by Django 4.1.7 on 2023-09-22 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0005_auto_20230922_1539"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="client",
        ),
    ]
