# Generated by Django 4.1.7 on 2023-09-22 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedbacks", "0006_remove_feedback_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="id",
        ),
        migrations.AddField(
            model_name="feedback",
            name="client",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedback",
            name="feedback_id",
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
