# Generated by Django 4.1.7 on 2023-09-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0007_remove_feedback_id_feedback_client_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="client",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="feedback_id",
        ),
        migrations.AddField(
            model_name="feedback",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=2,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
