# Generated by Django 4.1.7 on 2023-09-24 09:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Departments", "0002_department_client"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("department_name", "client")},
        ),
    ]
