# Generated by Django 4.2.7 on 2023-12-02 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Departments", "0003_alter_department_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("department_name",)},
        ),
    ]
