# Generated by Django 4.2.4 on 2023-08-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0002_alter_patient_updated_at"),
        ("doctors", "0002_alter_doctor_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTest",
            fields=[
                ("lab_test_id", models.AutoField(primary_key=True, serialize=False)),
                ("test_name", models.CharField(max_length=250)),
                ("test_date", models.DateField()),
                ("results", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
