# Generated by Django 4.1.7 on 2023-10-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="id",
        ),
        migrations.AlterField(
            model_name="package",
            name="package_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
