# Generated by Django 4.1.7 on 2023-10-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0004_remove_package_package_id_package_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="id",
        ),
        migrations.AddField(
            model_name="package",
            name="package_id",
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
