# Generated by Django 4.1.7 on 2023-10-15 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0006_alter_package_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="package",
            unique_together=set(),
        ),
    ]
