# Generated by Django 4.1.7 on 2023-10-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0008_alter_package_current_package_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="package_id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
