# Generated by Django 4.2.4 on 2023-08-19 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Invoices", "0002_invoice_patient_first_name_invoice_patient_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="patient_first_name",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="patient_last_name",
        ),
    ]
