# Generated by Django 4.1.7 on 2023-11-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
