# Generated by Django 4.1.7 on 2023-10-15 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0002_remove_package_id_alter_package_package_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="package",
            unique_together=set(),
        ),
    ]
