# Generated by Django 4.1.7 on 2023-10-15 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("packages", "0007_alter_package_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="current_package",
            field=models.CharField(
                choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")],
                default="Monthly",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="package",
            unique_together={("package_id", "client")},
        ),
    ]
