# Generated by Django 4.1.7 on 2023-11-21 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("packages", "0009_alter_package_package_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="package",
            unique_together={("package_name", "client")},
        ),
    ]
