# Generated by Django 4.2.4 on 2023-08-16 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescription",
            old_name="doctor_id",
            new_name="doctor",
        ),
        migrations.RenameField(
            model_name="prescription",
            old_name="patient_id",
            new_name="patient",
        ),
    ]
