# Generated by Django 4.1.7 on 2023-08-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Hospitals", "0001_initial"),
        ("Prescriptions", "0004_remove_prescription_doctor_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="client",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="Hospitals.hospital",
            ),
            preserve_default=False,
        ),
    ]
