# Generated by Django 4.1.7 on 2023-09-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Prescriptions", "0005_prescription_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="prescription_time",
            field=models.TimeField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="prescription",
            name="prescription_date",
            field=models.DateField(),
        ),
    ]
