# Generated by Django 4.1.7 on 2023-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Prescriptions", "0009_remove_prescription_prescription_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="prescription_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="prescription_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
