# Generated by Django 4.1.7 on 2023-11-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Prescriptions", "0010_prescription_prescription_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="prescription_date",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="prescription_time",
        ),
        migrations.AddField(
            model_name="prescription",
            name="prescription_date_time",
            field=models.DateTimeField(null=True),
        ),
    ]
