# Generated by Django 4.1.7 on 2023-09-24 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Nurses", "0003_alter_nurse_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nurse",
            name="department",
        ),
    ]
