# Generated by Django 4.1.7 on 2023-09-28 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Nurses", "0006_alter_nurse_department"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nurse",
            unique_together={("first_name", "last_name", "date_of_birth")},
        ),
    ]
