# Generated by Django 4.2.7 on 2023-12-02 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Prescriptions", "0001_initial"),
        ("Medicines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionDetail",
            fields=[
                (
                    "prescription_detail_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("dosage", models.CharField(max_length=250)),
                ("frequency", models.CharField(max_length=250)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Medicines.medicine",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Prescriptions.prescription",
                    ),
                ),
            ],
        ),
    ]
