# Generated by Django 4.1.7 on 2023-09-15 06:21

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):
    dependencies = [
        ("Prescriptions", "0006_prescription_prescription_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="prescription_time",
            field=models.TimeField(default=datetime.time(0, 0), verbose_name="Conversation Time"),
        ),
    ]
