# Generated by Django 4.1.7 on 2023-09-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Prescriptions", "0007_alter_prescription_prescription_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="prescription_date",
            field=models.DateField(auto_now_add=True, verbose_name="Conversation Date"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="prescription_time",
            field=models.TimeField(auto_now_add=True, verbose_name="Conversation Time"),
        ),
    ]
