# Generated by Django 4.1.7 on 2023-08-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0009_patient_client"),
        ("Beds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bed",
            name="patient",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
            ),
            preserve_default=False,
        ),
    ]
