# Generated by Django 4.1.7 on 2023-08-25 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_patient_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="client",
        ),
    ]
