# Generated by Django 4.2.4 on 2023-08-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Prescriptions", "0002_rename_doctor_id_prescription_doctor_and_more"),
        ("Medicines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionDetail",
            fields=[
                (
                    "prescription_detail_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("dosage", models.CharField(max_length=250)),
                ("frequency", models.CharField(max_length=250)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Medicines.medicine",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Prescriptions.prescription",
                    ),
                ),
            ],
        ),
    ]
