# Generated by Django 4.2.7 on 2023-12-02 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField(null=True)),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("Cardiology", "Cardiology"),
                            ("Dermatology", "Dermatology"),
                            ("Neurology", "Neurology"),
                            ("Orthopedics", "Orthopedics"),
                            ("Pediatrics", "Pediatrics"),
                            ("Ophthalmology", "Ophthalmology"),
                            ("Gynecology", "Gynecology"),
                            ("Urology", "Urology"),
                            ("Oncology", "Oncology"),
                            ("Psychiatry", "Psychiatry"),
                            ("ENT", "ENT"),
                        ],
                        max_length=255,
                    ),
                ),
                ("qualifications", models.TextField()),
                ("address", models.CharField(max_length=255)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctor_profile/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Departments.department",
                    ),
                ),
            ],
        ),
    ]
