# Generated by Django 4.1.7 on 2023-08-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Departments", "0002_department_client"),
        ("Hospitals", "0001_initial"),
        ("doctors", "0002_alter_doctor_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Hospitals.hospital",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doctor",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Departments.department"
            ),
        ),
    ]
