# Generated by Django 4.1.7 on 2023-08-22 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0003_doctor_client_alter_doctor_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="department",
        ),
    ]
