# Generated by Django 4.1.7 on 2023-08-25 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0005_doctor_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="department",
        ),
    ]
