# Generated by Django 4.1.7 on 2023-08-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0006_remove_doctor_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="department",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
