# Generated by Django 4.1.7 on 2023-09-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0007_doctor_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="doctor_profile/"),
        ),
    ]
