# Generated by Django 4.1.7 on 2023-09-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0008_doctor_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
