# Generated by Django 4.1.7 on 2023-09-24 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0009_alter_doctor_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="department",
        ),
    ]
