# Generated by Django 4.1.7 on 2023-08-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Hospitals", "0003_alter_hospital_email"),
        ("patients", "0006_remove_patient_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="client",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="Hospitals.hospital",
            ),
            preserve_default=False,
        ),
    ]
