# Generated by Django 4.1.7 on 2023-09-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0009_patient_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
