# Generated by Django 4.2.4 on 2023-08-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("Cardiology", "Cardiology"),
                            ("Dermatology", "Dermatology"),
                            ("Neurology", "Neurology"),
                            ("Orthopedics", "Orthopedics"),
                            ("Pediatrics", "Pediatrics"),
                            ("Ophthalmology", "Ophthalmology"),
                            ("Gynecology", "Gynecology"),
                            ("Urology", "Urology"),
                            ("Oncology", "Oncology"),
                            ("Psychiatry", "Psychiatry"),
                            ("ENT", "ENT"),
                        ],
                        max_length=255,
                    ),
                ),
                ("qualifications", models.TextField()),
                ("address", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
