# Generated by Django 4.1.7 on 2023-08-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Hospitals", "0001_initial"),
        ("Medicines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="client",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="Hospitals.hospital",
            ),
            preserve_default=False,
        ),
    ]
