# Generated by Django 4.1.7 on 2023-08-22 10:14

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "client_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("hospital_name", models.CharField(max_length=100)),
                ("owner_name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=100, unique=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Admin", "admin"),
                            ("Doctor", "doctor"),
                            ("Nurse", "nurse"),
                            ("Receptionist", "receptionist"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="user_profiles/"
                    ),
                ),
                (
                    "user_logo",
                    models.ImageField(blank=True, null=True, upload_to="user_logos/"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
