# Generated by Django 4.1.7 on 2023-08-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hospitals", "0002_alter_hospital_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
