# Generated by Django 4.1.7 on 2023-08-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hospitals", "0003_alter_hospital_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="access_token",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="hospital",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
