# Generated by Django 4.1.7 on 2023-08-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hospitals", "0004_hospital_access_token_hospital_refresh_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hospital",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
