# Generated by Django 4.1.7 on 2023-08-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hospitals", "0005_hospital_is_admin_hospital_last_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="name",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
