# Generated by Django 4.1.7 on 2023-08-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hospitals", "0007_hospital_groups_hospital_is_superuser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="hospital",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
