# Generated by Django 4.1.7 on 2023-09-14 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Hospitals", "0009_rename_is_superuser_hospital_is_admin"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hospital",
            unique_together={("email", "user_type")},
        ),
    ]
