# Generated by Django 4.1.7 on 2023-09-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hospitals", "0010_alter_hospital_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hospital",
            name="otp_code",
            field=models.CharField(default=2, max_length=6),
            preserve_default=False,
        ),
    ]
