# Generated by Django 4.1.7 on 2023-09-27 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Hospitals", "0011_hospital_is_verified_hospital_otp_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospital",
            old_name="otp_code",
            new_name="otp",
        ),
    ]
